### ISSUE TITLE
Circle clip does not work if the agent name has a single quote in it

### ISSUE THREAD

**Issue by simontegg** [holodex/app#110]
![screenshot - 100815 - 12 38 32](https://cloud.githubusercontent.com/assets/1574732/9157724/c15ecb5a-3f5c-11e5-8206-1378c52a7467.png)

``` mary-o'keeffe```
```

**Comment by ahdinosaur** [comment]
i reckon try url encoding https://github.com/holodex/app/blob/master/src/node_modules/graph-view/node-ui.js#L37 and https://github.com/holodex/app/blob/master/src/node_modules/graph-view/node-ui.js#L49.
