### ISSUE TITLE
Arrows overlap and obscure each other

### ISSUE THREAD

**Issue by simontegg** [holodex/app#112]
![screenshot - 120815 - 20 26 21](https://cloud.githubusercontent.com/assets/1574732/9219697/c810b21c-4130-11e5-90ca-b20ea88cf5a4.png)

Siince csv branch was merged in [cough] by the pull-requester [cough], default queries include both directions giving overlapping arrows (and potentially superfluous information)

**Comment by ahdinosaur** [comment]
eep, sorry didn't notice this. do you have any more information on why this might be happening? the only possible cause i can imagine is that the csv info is missing something that the yml data had.

**Comment by ahdinosaur** [comment]
this points to that we need a staging deploy setup, so we could check that for any possible issues before a production deploy, as in this case running the new setup locally would have required too much effort for you (due to the specific knowledge required of the change).

**Comment by ahdinosaur** [comment]
should be fixed in https://github.com/holodex/app/commit/ad1c63441557bc95b6a37ec4096f2aadd8bf7d65

**Comment by simontegg** [comment]
Sweet :+1:
