### ISSUE TITLE
`ui/light-theme.js` breaking on uglify

### ISSUE THREAD

**Issue by ahdinosaur** [holodex/app#119]
how to reproduce:

`./node_modules/.bin/browserify src/node_modules/ui/light-theme.js -t uglifyify`

/cc @simontegg

**Comment by ahdinosaur** [comment]
error message: `Unexpected token punc «(», expected punc «:» (line: 24, col: 21, pos: 742)`

**Comment by ahdinosaur** [comment]
@simontegg would you want me to get `babel` and `babelify` setup on 'master'? i can cherry-pick https://github.com/holodex/app/commit/e414f083bc1ac4a4a957de7eaf150820fe0198ad and add an app-level `babelify` transform

**Comment by simontegg** [comment]
that'd be cool.
