### ISSUE TITLE
on group page, UI renders basic list view of other agents the given group has a relationship with

### ISSUE THREAD

**Issue by simontegg** [holodex/app#2]
@ahdinosaur edits:

with an object of relationships the agent has indexed by type, for each type of relationship, render a section with the label of the relationship type and list of the other agents.

**Comment by ahdinosaur** [comment]
almost done, list view needs to intelligently handle contextual relationships (Enspiral Craftwork's stewardships).

**Comment by ahdinosaur** [comment]
remaining issue is now in https://github.com/holodex/app/issues/46, closing this.
