### ISSUE TITLE
use r-dom instead of JSX

### ISSUE THREAD

**Issue by ahdinosaur** [holodex/app#39]
[this is what it looks like in `list-view`](https://github.com/holodex/app/blob/master/src/node_modules/list-view/index.js). [r-dom on npm](https://npmjs.org/r-dom).

i think i'd prefer this as then it'd reduce the lag between server reloads where we're running the `node-jsx` transform on every require. also more javascript-y. :black_joker: 

@simontegg how do you feel about this?

**Comment by simontegg** [comment]
I feel good
