### ISSUE TITLE
enforce code style

### ISSUE THREAD

**Issue by ahdinosaur** [holodex/app#40]
should we do it or not?

i'm starting to think maybe we should.

possible code styles:
- [standard](https://github.com/feross/standard).

**Comment by simontegg** [comment]
I've started doing new files with standard style. Its nice.

**Comment by simontegg** [comment]
Placeholder comment. Alongside js code style we have React patterns and best practices:
- [React Patterns](https://github.com/planningcenter/react-patterns)
- [React best practices](http://aeflash.com/2015-02/react-tips-and-best-practices.html)

**Comment by ahdinosaur** [comment]
i reckon let's move to standard style as we churn code, i need to finish https://github.com/holodex/app/issues/40 before we can properly use the validator.

one discrepancy i've noticed in my person style: i prefer trailing commas. but hmm, maybe it's better to not have them, for example it's confusing when you can't put a trailing comma in

``` js
fn(
  arg1,
  arg2
)
``
```

**Comment by ahdinosaur** [comment]
at the end of #55, i moved us to be using standard. we should update the README with a standard badge.

**Comment by ahdinosaur** [comment]
done in 3519995fdfc2908ec3f6ba4c0753eaf183e05c68.
