### ISSUE TITLE
style - bigger avatars

### ISSUE THREAD

**Issue by mixmix** [holodex/app#43]
this is prettier : 

![selection_122](https://cloud.githubusercontent.com/assets/2665886/6569157/c1002efa-c749-11e4-9a71-7a12f2f6bf1a.png)
- no dropshadow
- 80px dia avatars

**Comment by mixmix** [comment]
with 40px you can't see who the person is

**Comment by simontegg** [comment]
I agree in this case, but there's other design context. What if there are 50+ nodes? What are the screen dimensions?

**Comment by mixmix** [comment]
these are valid for later. I want to make the app immediately more usable and sexy

**Comment by simontegg** [comment]
I'll merge your pr. 
We need to have a brief for Nanz and the current issue and these questions might be more usefully handled by her.

**Comment by mixmix** [comment]
true.
also, I tried to get into this and couldn't see what to modify the thing. maybe more pairing soon
