### ISSUE TITLE
add enspiral services data

### ISSUE THREAD

**Issue by simontegg** [holodex/app#52]

**Comment by ahdinosaur** [comment]
this is dependent on my `refactor-api` branch which has major changes to the data format.

**Comment by ahdinosaur** [comment]
data format is all ready (thanks to #55 and #57) at [holodex/enspiral-data](https://github.com/holodex/enspiral-data).

**Comment by simontegg** [comment]
choice

**Comment by ahdinosaur** [comment]
done
