### ISSUE TITLE
Site keeps reloading

### ISSUE THREAD

**Issue by simontegg** [holodex/app#54]
possibly related to `livereload:server`

some console output:

...
livereload:server LRWebSocketConnection(C5) received {"command":"hello","protocols":["http://livereload.com/protocols/official-6","http://livereload.com/protocols/official-7"],"ver":"2.0.8","snipver":"1"} +489ms
  wsio:hybi websocket writing +643ms {"command":"hello","protocols":["http://livereload.com/protocols/connection-check-1","http://livereload.com/protocols/official-7","http://livereload.com/protocols/saving-1"],"id":"default id","name":"default name","version":"1.0"}
...

....
  livereload:server LRWebSocketConnection(C5) received {"command":"info","plugins":{"less":{"disable":false,"version":"1.0"}},"url":"http://localhost:3000/"} +179ms
  wsio:hybi websocket writing +115ms {"command":"reload","path":".bundle.js","liveCSS":true}
  wsio:hybi websocket writing +136ms {"command":"reload","path":".bundle.js","liveCSS":true}
....

**Comment by ahdinosaur** [comment]
thanks for filing the bug. :bug: 

turns out it's because of watchify (see what happens when you call `./node_modules/.bin/watchify . -o src/assets/bundle.js -v` command). not sure why at the moment, but i'll work on a fix.

**Comment by ahdinosaur** [comment]
localized the bug into a [reproducible example](https://github.com/ahdinosaur/watchify-bug) and filed an issue with `watchify`: https://github.com/substack/watchify/issues/190.
