### ISSUE TITLE
reduce the size of the browser code

### ISSUE THREAD

**Issue by ahdinosaur** [holodex/app#56]
![the browser bundle is too damn big](http://i.imgur.com/kNcSJt0.jpg)

this isn't a huge priority, but i think it's something we should keep in mind if we want Holodex to be accessible to as many people as possible. the size will certainly move up and down with changes, so this issue is more about how we can take size snapshots and a reflection on the current size snapshot.

right now, our current (`refactor-api` branch) minified bundle size is 911.87 kB, which after gzip is 209.61 kB.

```
npm i -g pretty-bytes
npm run build
cat src/assets/bundle.js | wc -c | pretty-bytes
cat src/assets/bundle.js | gzip | wc -c | pretty-bytes
```

most of these bytes are not from our own code, it's from our dependencies. we can nicely visualize our dependencies with [disc](https://www.npmjs.com/package/disc), which allows us to browse the true size of Holodex [here](https://1ecfe398e320bb92e1e5e157b8ce7bf6841ab7d0.htmlb.in/).

```
npm i -g disc
./node_modules/.bin/browserify . --full-paths | ./node_modules/.bin/uglifyjs > src/assets/bundle.js
discify src/assets/bundle.js curl -sT- https://htmlb.in
```

some random notes on our current dependencies:
- `react` is massive at 279.2kB, wow (is `react` worth it over the slimmer [`virtual-dom`](https://github.com/Matt-Esch/virtual-dom)?)
- `react-bootstrap` is also decently sized at 87.8kB
- `lokijs` is reasonable at 42.3kB
- `webcola` is somewhat okay at 68.5kB (is `webcola` worth it over the slimmer [`ngraph.forcelayout`](https://github.com/anvaka/ngraph.forcelayout)?)
- we have two `readable-stream`s at ~20kB each
- `got` requires `browserify-zlib` at 62.2kB in order to gunzip the response.

these are open questions, i don't have any answers, nor is this really a big deal right now. :mouse2:

**Comment by ahdinosaur** [comment]
realistically, this should not be our focus.

development is a three stage process:
1. make it work
2. make it beautiful
3. make it fast

we should be cycling most between 1 and sometimes 2, only 3 if necessary.

**Comment by simontegg** [comment]
++ to your last comment.

Regarding ngraph, there's lots of pretty examples, but I'm more interested in stable examples. I strongly believe a graph-based UI needs stability (no matter what data is thrown at it) to be feasible. 

Its probably possible to get ngraph.forcelayout to stabilise for particular examples, this is [close](http://anvaka.github.io/ngraph/examples/pixi.js/06%20-%20Packaging/). But [this is too unstable](http://npm.anvaka.com/#/view/2d/browserify) for my liking. 

Unsure if this scales generically. Could look into it for later releases. Cola also has has other constraint optimisation features that could prove useful.

**Comment by simontegg** [comment]
Regarding virtual-dom, 

Still feel a bit burnt by mercury ;). Doesn't look bad. If there's some easy lifecycle methods I could be convinced. [relevant](https://github.com/Matt-Esch/virtual-dom/issues/85)

**Comment by simontegg** [comment]
I think we can do a lot by modularising `react-bootstrap` and/or shifting to uour own components

**Comment by ahdinosaur** [comment]
> I strongly believe a graph-based UI needs stability (no matter what data is thrown at it) to be feasible.

agreed. my main concern with `webcola` is about how we are maintaining a complicated fork that neither of us understand in order to use it. it works really well for now, but i wonder if we'd be better off using something less ideal and more simple to understand at this point. there's also a clear migration path if we go with the `ngraph` ecosystem, when we want to write a new layout engine we know what interface to write for and can easily swap out these subsystems.

> Regarding virtual-dom,

if we moved to `virtual-dom`, we'd also be missing out on the heaps of React components available that we don't have to write.

> I think we can do a lot by modularising react-bootstrap and/or shifting to uour own components

agreed, i don't think we really need bootstrap, we can easily pick and choose the components we need from the ecosystem.

**Comment by ahdinosaur** [comment]
ah, as an immediate step we can [require the `react-bootstrap` components directly](https://react-bootstrap.github.io/getting-started.html) with `require('react-bootstrap/ComponentName')`.

edit: woot, shaved off 85.19kB by doing the above.

**Comment by ahdinosaur** [comment]
useful tools for page speed metrics:
- [psi](https://www.npmjs.com/package/psi)
- [tmi](https://www.npmjs.com/package/tmi)

**Comment by ahdinosaur** [comment]
reduced the bundle by 15% by [adding `--screw-ie8 --mangle` to `uglifyjs`](https://github.com/holodex/app/commit/d691cd278415f3e5780730c8ba7bfc38a9fafbf8).

**Comment by simontegg** [comment]
sweet

**Comment by simontegg** [comment]
> If you set the NODE_ENV environment variable to 'production' when running browserify, a handful of React dev-only checks are stripped and the bumdle will be smaller. Also, you should make sure that you're minifying your bundle. React by itself is only 31k minified and gzipped, so your simple app shouldn't be much more than that.

https://groups.google.com/forum/#!topic/reactjs/Yr7QpI2vVfw
