### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by simontegg** [holodex/app#68]
![Imgur](http://i.imgur.com/J1EeUgj.png)

Version 8.0.5 (10600.5.3.1)

**Comment by ahdinosaur** [comment]
hmm, is this because of our [react hacks](https://github.com/holodex/app/tree/master/src/node_modules/react-svg-patch)?

**Comment by simontegg** [comment]
Posibly the react hacks but also could be from [these lines](https://github.com/holodex/app/blob/master/src%2Fnode_modules%2Fgraph-view%2Fgraph.js#L104) in `graph.js` 

If the latter, rendering the arrows as `svg:path` which I was going to do anyway should clear up the bug

**Comment by ahdinosaur** [comment]
is this still a bug after https://github.com/holodex/app/pull/95?

**Comment by simontegg** [comment]
Whoops. I haven't yet removed the now unnecessary `<defs>` code in `graph-view.js` that I think was causing it.
