### ISSUE TITLE
Test out new commonjsified Webcola!

### ISSUE THREAD

**Issue by simontegg** [holodex/app#80]
https://github.com/tgdwyer/WebCola/pull/108

**Comment by ahdinosaur** [comment]
@simontegg how do you feel about tackling this?

**Comment by simontegg** [comment]
I feel good about it :). I've almost got a proper pan zoom with matrix transforms working. Next was going to be splitting off the 'legend' from the 'query box'. Then I'll do the webcola test while mocking up the 'view more information about an agent' options

**Comment by ahdinosaur** [comment]
that is really awesome, keen. :sake:
