### ISSUE TITLE
[Process Improvement]: Tag and/or annotate each issue with metadata

### ISSUE THREAD

**Issue by simontegg** [holodex/app#85]
Value: When we annotate with metadata ('value', a time estimate, category) it becomes easier to feedback and prioritise tasks collectively. Its also easier to get a sense of where our focus is going as a group.

**Comment by ahdinosaur** [comment]
interesting discussion on this in https://github.com/nodejs/io.js/issues/26.

based on your suggestion, worth echoing

> I like the [Rust taxonomy](https://github.com/rust-lang/rust-wiki-backup/blob/master/Note-tag-label-names-and-definitions.md) where issues have area, effort, impact and priority tags. A simple documentation fix gets tagged A-docs + E-easy + I-papercut + P-low, a crash on OS X A-macos + E-hard + I-crash + P-high, etc. The multi-dimensional aspect makes it pretty effective.
