### ISSUE TITLE
Render arrows as svg:path and connect to role halos if present

### ISSUE THREAD

**Issue by simontegg** [holodex/app#89]
Value: 
Rewriting the arrows as svg:paths 
1. Arrow head markers are currently not the same color as their arrow.
2. arrowheads are potentially casuing the safari bug
1. Arrow heads are often obscured
2. Nanz has proposed a design where the arrow is connected to the source role halo for clarity.

**Comment by simontegg** [comment]
Expected delivery: 31/5

**Comment by ahdinosaur** [comment]
design by @nanz, reposted for posterity: 
![screen_shot_2015-04-22_at_10 00 52_am_360](https://cloud.githubusercontent.com/assets/719605/7910154/5408f2de-08a6-11e5-941b-b7d6572708af.png)

**Comment by simontegg** [comment]
Ta

**Comment by ahdinosaur** [comment]
implemented with https://github.com/holodex/app/pull/95.
